version: '3.1'

services:
  db:
    image: postgres
    container_name: pg1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/postgresql/data:/var/lib/postgresql/data