version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:7.5.0
    container_name: elasticsearch
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Asia/Shanghai"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  kibana:
    image: kibana:7.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    environment:
      - "I18N_LOCALE=zh-CN"
    networks:
      - esnet

networks:
  esnet:
    driver: bridge