version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
  oap:
    image: apache/skywalking-oap-server
    container_name: oap
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./config:/skywalking/config:ro
  ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 8081:8080
    environment:
      collector.ribbon.listOfServers: oap:12800
