version: '3.1'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql1
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/mysql1:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_general_ci'